In [23]:
import numpy as np
import pandas as pd

In [2]:
a = ["ali", 3 , "omar", False]
np.random.choice(a, size=(3,5))

array([['3', 'ali', 'omar', '3', '3'],
       ['omar', 'False', 'omar', '3', 'False'],
       ['False', '3', 'False', '3', 'omar']], dtype='<U21')

In [5]:
mat1 = np.ones((3,4))
mat2 = np.zeros((5,3))

np.savez("file.npz", ones_mat = mat1 , zeros_mat = mat2)

In [9]:
with np.load("file.npz") as file:
 mate1 = file["ones_mat"]
 mate2 = file["zeros_mat"]

print(mate1)
print("-----------------")
print(mate2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,4,5,6])  

np.allclose(v1, v2, atol=1)

True

Pandas ------------------------------------------

In [27]:
s =  pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [28]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}   
type(data)

list

In [29]:
df = pd.DataFrame(data)
df

   0    1    2
0  1  444  abc
1  2  555  def
2  3  666  ghi
3  4  444  xyz

In [32]:
cols = ['id','salary','department']
df2 = pd.DataFrame(data, columns=cols)
df2

   id  salary department
0   1     444        abc
1   2     555        def
2   3     666        ghi
3   4     444        xyz

In [11]:
df2.columns

Index(['id', 'salary', 'department'], dtype='str')

In [10]:
df2.id

0    1
1    2
2    3
3    4
Name: id, dtype: int64

In [38]:
df2.salary

0    444
1    555
2    666
3    444
Name: salary, dtype: int64

In [39]:
df2.department

0    abc
1    def
2    ghi
3    xyz
Name: department, dtype: str

In [40]:
df2.head()

   id  salary department
0   1     444        abc
1   2     555        def
2   3     666        ghi
3   4     444        xyz

In [41]:
df2.head(2)

   id  salary department
0   1     444        abc
1   2     555        def

In [12]:
df2.describe()

             id      salary
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000