In [90]:
import pandas as pd
import numpy as np

In [91]:
df = pd.read_csv('Titanic.csv')

In [92]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [93]:
from config import DROP_COL_Titanic
from preprocssing import drop_cols

In [94]:
drop_cols(df , DROP_COL_Titanic)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [95]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [96]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [97]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [98]:
df = drop_cols(df , DROP_COL_Titanic)

In [99]:
dtype = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({"Dtypes": dtype, "N_unique ": n_uniq})

           Dtypes  N_unique
Survived    int64          2
Pclass      int64          3
Sex           str          2
Age       float64         88
SibSp       int64          7
Parch       int64          7
Fare      float64        248
Cabin         str        147
Embarked      str          3

In [100]:
cols = ["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Cabin","Embarked"]
df[cols] = df[cols].astype("category")
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,category,category,category,category,category,category

In [101]:
def get_data_summary(df):
  return pd.DataFrame({"Dtype ":df.dtype, "N_uniques ": df.n_uniq}).T

In [102]:
null = df.isnull().sum()
ratio = (null/ df.shape[0])*100
ratio

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

In [103]:
pd.DataFrame({"null ":null, "ratio ": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467

In [104]:
df = df.dropna(subset =['Embarked'])

In [105]:
null = df.isnull().sum()
ratio = (null/ df.shape[0])*100

pd.DataFrame({"null ":null, "ratio ": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.00000,0.0
ratio,0.0,0.0,0.0,19.910011,0.0,0.0,0.0,77.27784,0.0

In [106]:
df.describe()

        Survived  Pclass   Sex    Age  SibSp  Parch    Fare    Cabin Embarked
count        889     889   889  712.0    889    889  889.00      202      889
unique         2       3     2   88.0      7      7  247.00      146        3
top            0       3  male   24.0      0      0    8.05  B96 B98        S
freq         549     491   577   30.0    606    676   43.00        4      644

In [ ]:
# Convert continuous columns back to numeric
num_cols = ["Age", "Fare"]
df[num_cols] = df[num_cols].apply(pd.to_numeric)

In [115]:
df.select_dtypes("number").columns

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    # print(Q1 ,Q3 )
    IQR = Q3 - Q1
    lower_fence = Q1 - 1.5*IQR
    upper_fence = Q1 + 1.5*IQR

    # lower_outliers = df[df[col] < lower_fence][col].values
    # print(lower_outliers)

    upper_outliers = df[df[col] > upper_fence][col].values
    print(upper_outliers)

[54.  58.  55.  66.  49.  65.  59.  71.  70.5 54.  51.  55.5 51.  61.
 56.  50.  58.  51.  59.  54.  62.  50.  52.  58.  63.  65.  50.  54.
 61.  60.  51.  50.  64.  52.  49.  65.  50.  48.  48.  56.  50.  63.
 58.  55.  71.  54.  54.  50.  50.  64.  62.  48.  62.  53.  54.  60.
 52.  49.  49.  61.  57.  80.  51.  48.  56.  58.  50.  70.  60.  60.
 52.  49.  48.  52.  50.  48.  70.  48.  51.  48.  57.  54.  49.  52.
 74.  51.  48.  56. ]
[ 71.2833  53.1     51.8625 263.     146.5208  82.1708  52.      76.7292
  61.9792  46.9     83.475   46.9     73.5     56.4958  47.1    263.
  61.175   63.3583  77.2875  52.     247.5208  73.5     77.2875  53.1
  79.2     66.6     61.3792  69.55    55.      56.4958  69.55    50.
 146.5208  69.55   113.275   76.2917  90.      83.475   90.      52.5542
  79.2     86.5    512.3292  79.65   153.4625 135.6333  77.9583  78.85
  91.0792 151.55   247.5208 151.55   110.8833 108.9     56.9292  83.1583
 262.375  164.8667 134.5     69.55   135.6333  57.9792 153.4625 133.65
  66.6    134.5    263.      55.      75.25    69.3     55.4417 135.6333
  82.1708 211.5    227.525   52.      73.5     46.9    120.     113.275
  90.      55.9    120.     263.      81.8583  89.1042  51.8625  52.
  46.9     91.0792  90.      49.5042  78.2667 151.55    86.5    108.9
  56.4958  59.4     93.5     57.9792 221.7792 106.425   49.5     71.
 106.425  110.8833 227.525   79.65    51.4792  55.9    110.8833  79.65
  79.2     78.2667  56.9292 153.4625  65.      52.5542  77.9583  69.3
  56.4958  76.7292  73.5    113.275  133.65    73.5     52.      52.
  46.9    512.3292  76.7292  46.9    211.3375  57.      56.4958 110.8833
 227.525  151.55    49.5042  52.     227.525   53.1    211.3375 512.3292
  78.85   262.375   71.      53.1     65.      86.5    120.      77.9583
 211.3375  57.      79.2     69.55   120.      53.1     93.5     56.4958
  83.1583  56.4958  69.55    89.1042 164.8667  69.55    50.4958  52.5542
  83.1583]

In [109]:
df.describe()

              Age        Fare
count  712.000000  889.000000
mean    29.642093   32.096681
std     14.492933   49.697504
min      0.420000    0.000000
25%     20.000000    7.895800
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200